system:
  station_id: "EJDER3200-ISTASYON-01"
  serial_port_pattern: "/dev/ttyUSB*"

sensors:
  distance:
    enabled: true
    # TEK TIRNAK KULLANILDI: '\d' artık bir hata vermeyecek.
    identifier_pattern: '^R\d{4}'
    baudrate: 9600
    mount_height_mm: 3700
    
  weight:
    enabled: true
    # TEK TIRNAK KULLANILDI: '\s' artık bir hata vermeyecek.
    identifier_pattern: '^\s*='
    baudrate: 9600
    measurement_area_m2: 1